# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Tag.create([
#     { name: 'GK', category: 'ポジション' },
#     { name: 'CB', category: 'ポジション' },
#     { name: 'SB', category: 'ポジション' },
#     { name: 'WB', category: 'ポジション' },
#     { name: 'A', category: 'ポジション' },
#     { name: 'CH', category: 'ポジション' },
#     { name: 'OMF', category: 'ポジション' },
#     { name: 'SH', category: 'ポジション' },
#     { name: 'WG', category: 'ポジション' },
#     { name: 'CF', category: 'ポジション' },
#     { name: '中央CB', category: 'ポジション' },
#     { name: '2CB', category: 'ポジション' },
#     { name: '3バック', category: 'ポジション' },
#     { name: '右', category: 'ポジション' },
#     { name: '左', category: 'ポジション' },
#     { name: '攻撃', category: '場面' },
#     { name: '守備', category: '場面' },
#     { name: '右足', category: '部位' },
#     { name: '左足', category: '部位' },
#     { name: 'インステップ', category: '部位' },
#     { name: 'イン', category: '部位' },
#     { name: 'アウト', category: '部位' },
#     { name: '頭', category: '部位' },
#     { name: '胸', category: '部位' },
#     { name: '肩', category: '部位' },
#     { name: '腰', category: '部位' },
#     { name: '脚', category: '部位' },
#     { name: '手', category: '部位' },
#     { name: '右利き', category: 'その他' },
#     { name: '左利き', category: 'その他' },
#     { name: 'ショート', category: 'その他' },
#     { name: 'ミドル', category: 'その他' },
#     { name: 'ロング', category: 'その他' },
#     { name: '参考資料', category: 'その他' },
#     { name: 'チーム', category: 'その他' },
#     { name: 'passion', category: 'その他' },
#     { name: '⑩', category: 'その他' },
#     { name: '珍プレー', category: 'その他' },
#     { name: 'beleza', category: 'その他' },
#     ])
    
# Tag.create([
#     { name: '技術', category: '技術' },
#     { name: '股抜き', category: '技術' },
#     { name: 'シャペウ', category: '技術' },
#     { name: '踏込み', category: '技術' },
#     { name: '懐', category: '技術' },
#     { name: '幅', category: '技術' },
#     { name: '切返し', category: '技術' },
#     { name: 'ターン', category: '技術' },
#     { name: 'ブロック', category: '技術' },
#     { name: '相手ランニングコースを防ぐ', category: '技術' },
#     { name: 'トラップ', category: '技術' },
#     { name: '前方', category: '技術' },
#     { name: '後方', category: '技術' },
#     { name: 'トラップでかわす', category: '技術' },
#     { name: '前を向く', category: '技術' },
#     { name: '浮かせてかわす', category: '技術' },
#     { name: '相手間侵入', category: '技術' },
#     { name: 'オープンスタンス', category: '技術' },
#     { name: 'ため', category: '技術' },
#     { name: '釣り球', category: '技術' },
#     { name: '回り込み', category: '技術' },
#     { name: 'キックフェイント', category: '技術' },
#     { name: 'ドリブル', category: '技術' },
#     { name: 'またぎ', category: '技術' },
#     { name: '間合いでかわす', category: '技術' },
#     { name: '相手脇を抜く', category: '技術' },
    
#     { name: 'PK', category: 'プレー' },
#     { name: 'FK', category: 'プレー' },
#     { name: 'CK', category: 'プレー' },
#     { name: 'ゴールキック', category: 'プレー' },
#     { name: 'GKスタート', category: 'プレー' },
#     { name: 'B-UP', category: 'プレー' },
#     { name: 'スローイン', category: 'プレー' },
#     { name: 'カウンターアタック', category: 'プレー' },
#     { name: '崩し', category: 'プレー' },
#     { name: 'ドリブル侵入', category: 'プレー' },
#     { name: '中央突破', category: 'プレー' },
#     { name: 'インナーラップ', category: 'プレー' },
#     { name: 'オーバーラップ', category: 'プレー' },
#     { name: 'カットイン', category: 'プレー' },
#     { name: 'ワンツー', category: 'プレー' },
#     { name: '３人目の動き', category: 'プレー' },
#     { name: 'オフ動き', category: 'プレー' },
#     { name: '足元→裏', category: 'プレー' },
#     { name: '裏→足元', category: 'プレー' },
    
#     { name: 'キック', category: 'キック' },
#     { name: '縦回転', category: 'キック' },
#     { name: '無回転', category: 'キック' },
#     { name: 'イン回転', category: 'キック' },
#     { name: 'アウト回転', category: 'キック' },
#     { name: 'カーブ', category: 'キック' },
#     { name: 'ループ', category: 'キック' },
#     { name: 'パントキック', category: 'キック' },
    
#     { name: 'シュート', category: 'シュート' },
#     { name: 'ゴール', category: 'シュート' },
#     { name: '１対１', category: 'シュート' },
#     { name: 'ダイレクトシュート', category: 'シュート' },
#     { name: 'ボレーシュート', category: 'シュート' },
#     { name: 'ドリブルシュート', category: 'シュート' },
#     { name: 'ヘディングシュート', category: 'シュート' },
    
#     { name: 'クロス', category: 'クロス' },
#     { name: 'アーリー', category: 'クロス' },
#     { name: 'マイナス', category: 'クロス' },
#     { name: 'ニア', category: 'クロス' },
#     { name: 'ファー', category: 'クロス' },
#     { name: 'ダイアゴナル', category: 'クロス' },
#     { name: 'GK越え', category: 'クロス' },
    
#     { name: 'パス', category: 'パス' },
#     { name: 'フィード', category: 'パス' },
#     { name: 'スルーパス', category: 'パス' },
#     { name: '深いパス', category: 'パス' },
#     { name: '味方外側スペース', category: 'パス' },
#     { name: '置き球', category: 'パス' },
#     { name: '相手最終ライン突破', category: 'パス' },
#     { name: '相手最終ライン背後', category: 'パス' },
#     { name: 'ヒールパス', category: 'パス' },
    
#     { name: 'ラインコントロール', category: '守備' },
#     { name: 'カウンター対応', category: '守備' },
#     { name: 'クロス対応', category: '守備' },
#     { name: 'ロングパス対応', category: '守備' },
#     { name: 'ダイアゴナルパス対応', category: '守備' },
#     { name: '背後パス対応', category: '守備' },
#     { name: '１対２対応', category: '守備' },
#     { name: '攻→守', category: '守備' },
#     { name: 'プレッシング', category: '守備' },
#     { name: 'ワイドプレス', category: '守備' },
#     { name: '引き込み', category: '守備' },
#     { name: 'チャレンジ＆カバー', category: '守備' },
#     { name: 'ボール奪取', category: '守備' },
#     { name: 'スライディング', category: '守備' },
#     { name: 'パスカット', category: '守備' },
#     { name: 'シュートブロック', category: '守備' },
#     { name: 'プレスバック', category: '守備' },
#     { name: '二度追い', category: '守備' },
#     { name: 'シュートストップ', category: '守備' },
#     { name: 'ブレイクアウェイ', category: '守備' },
#     ])

# Tag.create([
#     { name: 'Aサード', category: 'エリア' },
#     { name: 'Mサード', category: 'エリア' },
#     { name: 'Dサード', category: 'エリア' },
#     { name: '中央', category: 'エリア' },
#     { name: '右サイド', category: 'エリア' },
#     { name: '左サイド', category: 'エリア' },
#     { name: 'A1', category: 'エリア' },
#     { name: 'A2', category: 'エリア' },
#     { name: 'A3', category: 'エリア' },
#     { name: 'A4', category: 'エリア' },
#     { name: 'A5', category: 'エリア' },
#     { name: 'A6', category: 'エリア' },
#     { name: 'B1', category: 'エリア' },
#     { name: 'B2', category: 'エリア' },
#     { name: 'B3', category: 'エリア' },
#     { name: 'B4', category: 'エリア' },
#     { name: 'B5', category: 'エリア' },
#     { name: 'B6', category: 'エリア' },
#     { name: 'C1', category: 'エリア' },
#     { name: 'C2', category: 'エリア' },
#     { name: 'C3', category: 'エリア' },
#     { name: 'C4', category: 'エリア' },
#     { name: 'C5', category: 'エリア' },
#     { name: 'C6', category: 'エリア' },
#     { name: 'D1', category: 'エリア' },
#     { name: 'D2', category: 'エリア' },
#     { name: 'D3', category: 'エリア' },
#     { name: 'D4', category: 'エリア' },
#     { name: 'D5', category: 'エリア' },
#     { name: 'D6', category: 'エリア' },
#     { name: 'E1', category: 'エリア' },
#     { name: 'E2', category: 'エリア' },
#     { name: 'E3', category: 'エリア' },
#     { name: 'E4', category: 'エリア' },
#     { name: 'E5', category: 'エリア' },
#     { name: 'E6', category: 'エリア' },
#     { name: 'F1', category: 'エリア' },
#     { name: 'F2', category: 'エリア' },
#     { name: 'F3', category: 'エリア' },
#     { name: 'F4', category: 'エリア' },
#     { name: 'F5', category: 'エリア' },
#     { name: 'F6', category: 'エリア' },
#     { name: 'G1', category: 'エリア' },
#     { name: 'G2', category: 'エリア' },
#     { name: 'G3', category: 'エリア' },
#     { name: 'G4', category: 'エリア' },
#     { name: 'G5', category: 'エリア' },
#     { name: 'G6', category: 'エリア' },
#     { name: 'H1', category: 'エリア' },
#     { name: 'H2', category: 'エリア' },
#     { name: 'H3', category: 'エリア' },
#     { name: 'H4', category: 'エリア' },
#     { name: 'H5', category: 'エリア' },
#     { name: 'H6', category: 'エリア' },
    
#     ])